version: '3'
services:
  chrome:
    image: browserless/chrome:latest
    ports:
      - '3001:3000'
      - '9222:9222'
    environment:
      - CONNECTION_TIMEOUT=60000
      - MAX_CONCURRENT_SESSIONS=10
    restart: always
